### ISSUE TITLE
Error in Synchronizer class

### ISSUE THREAD

**Issue by mialje03** [inxilpro/Galahad-MailChimp-Synchronizer#2]
bug fix on function processMailChimpUsers

![screen shot 2015-03-25 at 12 24 50 pm](https://cloud.githubusercontent.com/assets/6468165/6833398/fe9adcc8-d2e9-11e4-9e9c-df5302e3070c.png)

**Comment by inxilpro** [comment]
Want to submit a pull request?

**Comment by mialje03** [comment]
done!

https://github.com/inxilpro/Galahad-MailChimp-Synchronizer/pull/3

**Comment by mialje03** [comment]
Thanks btw! very useful library

**Comment by inxilpro** [comment]
Merged.  Glad you found it useful — I've actually stopped using it, but it's nice to know that it's still getting some use :)
